# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ohdc/v0/relay.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ohdc/v0/relay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ohdc.v0 import ohdc_pb2 as ohdc_dot_v0_dot_ohdc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ohdc/v0/relay.proto\x12\x07ohdc.v0\x1a\x12ohdc/v0/ohdc.proto\"I\n\x0fRegisterRequest\x12\x18\n\x10storage_cert_der\x18\x01 \x01(\x0c\x12\x12\n\x05label\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_label\"Z\n\x10RegisterResponse\x12\x1a\n\x12registration_token\x18\x01 \x01(\t\x12\x16\n\x0erendezvous_url\x18\x02 \x01(\t\x12\x12\n\npin_sha256\x18\x03 \x01(\x0c\"8\n\x1aRefreshRegistrationRequest\x12\x1a\n\x12registration_token\x18\x01 \x01(\t\"5\n\x1bRefreshRegistrationResponse\x12\x16\n\x0evalid_until_ms\x18\x01 \x01(\x03\"F\n\x10HeartbeatRequest\x12\x1a\n\x12registration_token\x18\x01 \x01(\t\x12\x16\n\x0e\x63lient_time_ms\x18\x02 \x01(\x03\"+\n\x11HeartbeatResponse\x12\x16\n\x0eserver_time_ms\x18\x01 \x01(\x03\"/\n\x11\x44\x65registerRequest\x12\x1a\n\x12registration_token\x18\x01 \x01(\t\"0\n\x12\x44\x65registerResponse\x12\x1a\n\x12\x64\x65registered_at_ms\x18\x01 \x01(\x03\"@\n\x0bTunnelFrame\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0c\n\x04kind\x18\x03 \x01(\t2\xfa\x02\n\x0cRelayService\x12?\n\x08Register\x12\x18.ohdc.v0.RegisterRequest\x1a\x19.ohdc.v0.RegisterResponse\x12`\n\x13RefreshRegistration\x12#.ohdc.v0.RefreshRegistrationRequest\x1a$.ohdc.v0.RefreshRegistrationResponse\x12\x42\n\tHeartbeat\x12\x19.ohdc.v0.HeartbeatRequest\x1a\x1a.ohdc.v0.HeartbeatResponse\x12\x45\n\nDeregister\x12\x1a.ohdc.v0.DeregisterRequest\x1a\x1b.ohdc.v0.DeregisterResponse\x12<\n\nOpenTunnel\x12\x14.ohdc.v0.TunnelFrame\x1a\x14.ohdc.v0.TunnelFrame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ohdc.v0.relay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=52
  _globals['_REGISTERREQUEST']._serialized_end=125
  _globals['_REGISTERRESPONSE']._serialized_start=127
  _globals['_REGISTERRESPONSE']._serialized_end=217
  _globals['_REFRESHREGISTRATIONREQUEST']._serialized_start=219
  _globals['_REFRESHREGISTRATIONREQUEST']._serialized_end=275
  _globals['_REFRESHREGISTRATIONRESPONSE']._serialized_start=277
  _globals['_REFRESHREGISTRATIONRESPONSE']._serialized_end=330
  _globals['_HEARTBEATREQUEST']._serialized_start=332
  _globals['_HEARTBEATREQUEST']._serialized_end=402
  _globals['_HEARTBEATRESPONSE']._serialized_start=404
  _globals['_HEARTBEATRESPONSE']._serialized_end=447
  _globals['_DEREGISTERREQUEST']._serialized_start=449
  _globals['_DEREGISTERREQUEST']._serialized_end=496
  _globals['_DEREGISTERRESPONSE']._serialized_start=498
  _globals['_DEREGISTERRESPONSE']._serialized_end=546
  _globals['_TUNNELFRAME']._serialized_start=548
  _globals['_TUNNELFRAME']._serialized_end=612
  _globals['_RELAYSERVICE']._serialized_start=615
  _globals['_RELAYSERVICE']._serialized_end=993
# @@protoc_insertion_point(module_scope)
