#!/usr/bin/env python3
"""Generate CSS variables and Kotlin Compose color constants from
`tokens.json`.

`tokens.json` is the single source of truth for the OHD app palette
(NOT the logos — those carry their own colors as authored in
Inkscape). This script projects it into two generated files:

  - a `:root { --token: value; }` CSS block for cord-web / landing
  - an `object OhdColorsGenerated` with `Color(0xAARRGGBB)` constants
    for Connect Android

Both outputs are committed and idempotent; rerun after editing
tokens.json. The generated files carry a do-not-edit banner pointing
back here.
"""

from __future__ import annotations
import argparse
import json
import re
import sys
from pathlib import Path


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def kebab(name: str) -> str:
    return name.replace("_", "-")


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def color_value(entry: dict) -> str | None:
    """Return the printable CSS value for a color entry (hex or rgba)."""
    if "hex" in entry:
        return entry["hex"]
    if "rgba" in entry:
        return entry["rgba"]
    return None


def hex_to_argb(hex_str: str) -> str | None:
    """`#e11d2a` → `0xFFE11D2A`. Returns None for non-hex (rgba) values."""
    m = re.fullmatch(r"#([0-9a-fA-F]{6})([0-9a-fA-F]{2})?", hex_str.strip())
    if not m:
        return None
    rgb = m.group(1).upper()
    alpha = (m.group(2) or "FF").upper()
    return f"0x{alpha}{rgb}"


def gen_css(tokens: dict) -> str:
    lines = [
        "/* GENERATED by spec/brand/tokens.py from spec/brand/tokens.json —",
        "   do not edit by hand. Run `make tokens` in spec/brand/ to regenerate. */",
        ":root {",
    ]
    for name, entry in tokens["color"].items():
        val = color_value(entry)
        if val is None:
            continue
        lines.append(f"  --{kebab(name)}: {val};")
    for name, val in tokens.get("radius", {}).items():
        lines.append(f"  --radius-{kebab(name)}: {val};")
    for name, val in tokens.get("shadow", {}).items():
        lines.append(f"  --shadow-{kebab(name)}: {val};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_kotlin(tokens: dict) -> str:
    lines = [
        "// GENERATED by spec/brand/tokens.py from spec/brand/tokens.json —",
        "// do not edit by hand. Run `make tokens` in spec/brand/ to regenerate.",
        "package com.ohd.connect.ui.theme",
        "",
        "import androidx.compose.ui.graphics.Color",
        "",
        "/**",
        " * Brand palette projected from the canonical spec/brand/tokens.json.",
        " * Compose-side counterpart of cord-web's tokens.generated.css. The",
        " * hand-authored OhdColors object may alias these; this file only",
        " * carries the raw token values so a palette change is a single",
        " * `make tokens` away.",
        " */",
        "object OhdColorsGenerated {",
    ]
    for name, entry in tokens["color"].items():
        hex_val = entry.get("hex")
        if not hex_val:
            # rgba-only tokens (accent_tint) can't be a plain Color const;
            # emit a comment so the omission is visible.
            lines.append(f"    // {pascal(name)}: rgba token, compose at call site")
            continue
        argb = hex_to_argb(hex_val)
        if argb is None:
            continue
        lines.append(f"    val {pascal(name)} = Color({argb})")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("tokens", type=Path)
    ap.add_argument("--css", type=Path)
    ap.add_argument("--kotlin", type=Path)
    args = ap.parse_args()

    tokens = load(args.tokens)

    if args.css:
        args.css.parent.mkdir(parents=True, exist_ok=True)
        args.css.write_text(gen_css(tokens), encoding="utf-8")
        print(f"  wrote {args.css}")
    if args.kotlin:
        # Only write if the Android tree exists, so the script is usable
        # in a checkout without the app.
        if args.kotlin.parent.exists():
            args.kotlin.write_text(gen_kotlin(tokens), encoding="utf-8")
            print(f"  wrote {args.kotlin}")
        else:
            print(f"  skip {args.kotlin} (parent dir absent)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
