package com.ohd.emergency.data.ohdc

import android.content.Context
import com.ohd.emergency.data.CaseVault
import com.ohd.emergency.data.OperatorSession

/**
 * Singleton accessor for the [OhdcClient]. Lazily builds the client
 * once the operator's relay base URL is known + the OperatorSession has
 * a bearer.
 *
 * # Relay base URL resolution
 *
 * Resolution priority:
 *   1. Build-time `BuildConfig.OHD_EMERGENCY_RELAY_BASE` (set by Gradle
 *      property `-Pohd.emergency.relay.base=https://relay.ems-prague.cz`).
 *   2. `OperatorSession.relayBaseUrl(ctx)` — if a deployment learned the
 *      relay URL out-of-band (QR code at shift-in, fleet provisioning).
 *   3. Hard-coded dev fallback `http://10.0.2.2:8443` — Android emulator
 *      loopback to a relay running on the developer's host.
 *
 * The grant token comes from [CaseVault.activeCase] — it's only set
 * during an active case and is dropped on case close.
 */
object OhdcClientFactory {

    @Volatile
    private var cached: OhdcClient? = null

    @Volatile
    private var cachedBaseUrl: String? = null

    /**
     * Build (or return the cached) [OhdcClient]. Re-builds if the relay
     * URL has changed since the last build (e.g. shift-out on tablet A,
     * shift-in on tablet B with a different operator).
     */
    fun get(ctx: Context): OhdcClient {
        val baseUrl = resolveBaseUrl(ctx)
        val existing = cached
        if (existing != null && cachedBaseUrl == baseUrl) return existing
        synchronized(this) {
            val again = cached
            if (again != null && cachedBaseUrl == baseUrl) return again
            val built = OhdcClient(
                baseUrl = baseUrl,
                operatorBearerProvider = { OperatorSession.bearer(ctx) },
                grantTokenProvider = { CaseVault.activeCase.value?.grantToken },
            )
            cached = built
            cachedBaseUrl = baseUrl
            return built
        }
    }

    /**
     * Drop the cached client. Called on operator sign-out so the next
     * call rebuilds against fresh credentials and (potentially) a new
     * base URL.
     */
    fun reset() {
        synchronized(this) {
            cached = null
            cachedBaseUrl = null
        }
    }

    /**
     * Resolution order documented above. Defaults to the dev loopback
     * because the v0 demo runs against a developer's local relay.
     */
    private fun resolveBaseUrl(ctx: Context): String {
        // Operator-supplied URL takes precedence so a deployment can
        // override the build-baked default at runtime (per-fleet
        // provisioning flows).
        val fromSession = OperatorSession.relayBaseUrl(ctx)
        if (!fromSession.isNullOrBlank()) return fromSession
        // BuildConfig field is generated by app/build.gradle.kts. We
        // read it reflectively to avoid a hard compile-time dep on the
        // build flavor (tests pass `null` and rely on the fallback).
        val fromBuild = readBuildConfigStringOrNull("com.ohd.emergency.BuildConfig", "OHD_EMERGENCY_RELAY_BASE")
        if (!fromBuild.isNullOrBlank()) return fromBuild
        return "http://10.0.2.2:8443"
    }

    private fun readBuildConfigStringOrNull(className: String, fieldName: String): String? = try {
        val cls = Class.forName(className)
        val field = cls.getDeclaredField(fieldName)
        field.isAccessible = true
        field.get(null) as? String
    } catch (_: Throwable) {
        null
    }
}
