// GENERATED by spec/brand/tokens.py from spec/brand/tokens.json —
// do not edit by hand. Run `make tokens` in spec/brand/ to regenerate.
package com.ohd.connect.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Brand palette projected from the canonical spec/brand/tokens.json.
 * Compose-side counterpart of cord-web's tokens.generated.css. The
 * hand-authored OhdColors object may alias these; this file only
 * carries the raw token values so a palette change is a single
 * `make tokens` away.
 */
object OhdColorsGenerated {
    val BrandRed = Color(0xFFE11D2A)
    val DeepRed = Color(0xFFB62121)
    // AccentTint: rgba token, compose at call site
    val Ink = Color(0xFF202020)
    val Paper = Color(0xFFF1F1F1)
    val Muted = Color(0xFF5A5A5A)
    val Faint = Color(0xFF8A8A8A)
    val Line = Color(0xFFE5E5E5)
    val LineStrong = Color(0xFFD6D6D6)
    val SurfaceAlt = Color(0xFFF5F5F6)
    val White = Color(0xFFFFFFFF)
    val Black = Color(0xFF000000)
}
