// Generated by storage/tools/regen_migrations.py from
// spec/registry/metrics.toml. Do not hand-edit — your changes will be
// overwritten on the next regen pass. Edit the TOML instead and re-run:
//
//     python3 storage/tools/regen_migrations.py
//
// Schema version: 1
package com.ohd.connect.data

/**
 * One channel inside a metric (a leaf scalar the user writes per event).
 *
 * `path` is the storage-side channel path (often equal to `name`, but for
 * `medication.taken` channels it's prefixed with `med.` per the existing
 * migration). `unit` is the storage unit, not the user-facing one — for
 * user-toggleable display units see [MetricDef.unitOptions].
 */
data class ChannelDef(
    val name: String,
    val valueType: String,
    val unit: String?,
    val path: String,
)

/**
 * One metric (a single event_type the user can record).
 *
 * Generated from `spec/registry/metrics.toml`. `discoverableInQuickLog`
 * surfaces the row in `MeasurementScreen.QuickMeasures`. `unitOptions` and
 * `defaultUnit` are user-facing toggle values (e.g. mmol/L vs mg/dL), not
 * channel storage units.
 */
data class MetricDef(
    val namespace: String,
    val name: String,
    val description: String,
    val sensitivity: String,
    val discoverableInQuickLog: Boolean,
    val unitOptions: List<String>,
    val defaultUnit: String?,
    val channels: List<ChannelDef>,
) {
    /** Fully qualified event-type string used by `StorageRepository.putEvent`. */
    val eventType: String get() = "$namespace.$name"
}

/**
 * Compile-time mirror of the canonical metrics registry.
 *
 * Lookup helpers:
 *  - [byEventType] resolves a flat `"namespace.name"` string (the form used
 *    on the wire / in storage) back to its [MetricDef]. Returns null for
 *    unknown event types (e.g. runtime-registered custom metrics).
 *  - [bySymptomName] short-circuits the `symptom.<name>` lookup used by
 *    SymptomLogScreen, where the caller has the bare snake-case symptom
 *    name (e.g. "headache") rather than the fully qualified event type.
 *  - [quickMeasures] returns the rows that surface in `MeasurementScreen`'s
 *    QUICK MEASURES list, in declaration order.
 */
object MetricsRegistry {
    /** Schema version mirrored from `metrics.toml`. */
    const val SCHEMA_VERSION: Int = 1

    val all: List<MetricDef> = listOf(
        MetricDef(
            namespace = "measurement",
            name = "blood_pressure",
            description = "Blood pressure (Connect Android)",
            sensitivity = "general",
            discoverableInQuickLog = true,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "systolic_mmhg",
                    valueType = "real",
                    unit = "mmHg",
                    path = "systolic_mmhg",
                ),
                ChannelDef(
                    name = "diastolic_mmhg",
                    valueType = "real",
                    unit = "mmHg",
                    path = "diastolic_mmhg",
                ),
            ),
        ),
        MetricDef(
            namespace = "measurement",
            name = "glucose",
            description = "Blood glucose (Connect Android)",
            sensitivity = "general",
            discoverableInQuickLog = true,
            unitOptions = listOf("mmol/L", "mg/dL"),
            defaultUnit = "mmol/L",
            channels = listOf(
                ChannelDef(
                    name = "value",
                    valueType = "real",
                    unit = null,
                    path = "value",
                ),
                ChannelDef(
                    name = "unit",
                    valueType = "text",
                    unit = null,
                    path = "unit",
                ),
            ),
        ),
        MetricDef(
            namespace = "measurement",
            name = "weight",
            description = "Body weight (Connect Android + Health Connect)",
            sensitivity = "general",
            discoverableInQuickLog = true,
            unitOptions = listOf("kg", "lb"),
            defaultUnit = "kg",
            channels = listOf(
                ChannelDef(
                    name = "value",
                    valueType = "real",
                    unit = null,
                    path = "value",
                ),
                ChannelDef(
                    name = "unit",
                    valueType = "text",
                    unit = null,
                    path = "unit",
                ),
                ChannelDef(
                    name = "kg",
                    valueType = "real",
                    unit = "kg",
                    path = "kg",
                ),
            ),
        ),
        MetricDef(
            namespace = "measurement",
            name = "temperature",
            description = "Body temperature (Connect Android + Health Connect)",
            sensitivity = "general",
            discoverableInQuickLog = true,
            unitOptions = listOf("°C", "°F"),
            defaultUnit = "°C",
            channels = listOf(
                ChannelDef(
                    name = "value",
                    valueType = "real",
                    unit = null,
                    path = "value",
                ),
                ChannelDef(
                    name = "unit",
                    valueType = "text",
                    unit = null,
                    path = "unit",
                ),
                ChannelDef(
                    name = "celsius",
                    valueType = "real",
                    unit = "C",
                    path = "celsius",
                ),
            ),
        ),
        MetricDef(
            namespace = "measurement",
            name = "heart_rate",
            description = "Heart rate sample (Health Connect)",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "bpm",
                    valueType = "real",
                    unit = "bpm",
                    path = "bpm",
                ),
            ),
        ),
        MetricDef(
            namespace = "measurement",
            name = "urine_strip",
            description = "Urine dipstick reading (Connect Android UrineStripScreen)",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "glucose",
                    valueType = "text",
                    unit = null,
                    path = "glucose",
                ),
                ChannelDef(
                    name = "ph",
                    valueType = "text",
                    unit = null,
                    path = "ph",
                ),
                ChannelDef(
                    name = "protein",
                    valueType = "text",
                    unit = null,
                    path = "protein",
                ),
                ChannelDef(
                    name = "leukocytes",
                    valueType = "text",
                    unit = null,
                    path = "leukocytes",
                ),
            ),
        ),
        MetricDef(
            namespace = "measurement",
            name = "spo2",
            description = "Oxygen saturation (Health Connect)",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "percentage",
                    valueType = "real",
                    unit = "%",
                    path = "percentage",
                ),
            ),
        ),
        MetricDef(
            namespace = "measurement",
            name = "pain",
            description = "Pain score NRS 0-10 (Connect Android)",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "location",
                    valueType = "text",
                    unit = null,
                    path = "location",
                ),
                ChannelDef(
                    name = "severity_nrs",
                    valueType = "real",
                    unit = null,
                    path = "severity_nrs",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
            ),
        ),
        MetricDef(
            namespace = "medication",
            name = "taken",
            description = "Medication dose taken (Connect Android)",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "name",
                    valueType = "text",
                    unit = null,
                    path = "med.name",
                ),
                ChannelDef(
                    name = "dose",
                    valueType = "real",
                    unit = null,
                    path = "med.dose",
                ),
                ChannelDef(
                    name = "unit",
                    valueType = "text",
                    unit = null,
                    path = "med.unit",
                ),
            ),
        ),
        MetricDef(
            namespace = "food",
            name = "eaten",
            description = "Food intake (Connect Android FoodDetail)",
            sensitivity = "lifestyle",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "name",
                    valueType = "text",
                    unit = null,
                    path = "name",
                ),
                ChannelDef(
                    name = "grams",
                    valueType = "real",
                    unit = "g",
                    path = "grams",
                ),
                ChannelDef(
                    name = "kcal",
                    valueType = "real",
                    unit = "kcal",
                    path = "kcal",
                ),
                ChannelDef(
                    name = "carbs_g",
                    valueType = "real",
                    unit = "g",
                    path = "carbs_g",
                ),
                ChannelDef(
                    name = "protein_g",
                    valueType = "real",
                    unit = "g",
                    path = "protein_g",
                ),
                ChannelDef(
                    name = "fat_g",
                    valueType = "real",
                    unit = "g",
                    path = "fat_g",
                ),
                ChannelDef(
                    name = "sugar_g",
                    valueType = "real",
                    unit = "g",
                    path = "sugar_g",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "headache",
            description = "Headache",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "migraine",
            description = "Migraine",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "fatigue",
            description = "Fatigue",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "nausea",
            description = "Nausea",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "dizziness",
            description = "Dizziness",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "cough",
            description = "Cough",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "sore_throat",
            description = "Sore throat",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "fever",
            description = "Fever",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "stomach_pain",
            description = "Stomach pain",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "joint_pain",
            description = "Joint pain",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "back_pain",
            description = "Back pain",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "shortness_of_breath",
            description = "Shortness of breath",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "anxiety",
            description = "Anxiety",
            sensitivity = "mental_health",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "insomnia",
            description = "Insomnia",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "symptom",
            name = "other",
            description = "Other (free-text)",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "severity",
                    valueType = "real",
                    unit = null,
                    path = "severity",
                ),
                ChannelDef(
                    name = "severity_label",
                    valueType = "text",
                    unit = null,
                    path = "severity_label",
                ),
                ChannelDef(
                    name = "notes",
                    valueType = "text",
                    unit = null,
                    path = "notes",
                ),
            ),
        ),
        MetricDef(
            namespace = "activity",
            name = "steps",
            description = "Step count (Health Connect)",
            sensitivity = "lifestyle",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "count",
                    valueType = "int",
                    unit = null,
                    path = "count",
                ),
            ),
        ),
        MetricDef(
            namespace = "activity",
            name = "sleep",
            description = "Sleep session (Health Connect)",
            sensitivity = "general",
            discoverableInQuickLog = false,
            unitOptions = emptyList(),
            defaultUnit = null,
            channels = listOf(
                ChannelDef(
                    name = "duration_minutes",
                    valueType = "int",
                    unit = "min",
                    path = "duration_minutes",
                ),
            ),
        ),
    )

    private val byType: Map<String, MetricDef> = all.associateBy { it.eventType }

    /** Resolve a flat `"namespace.name"` string. */
    fun byEventType(type: String): MetricDef? = byType[type]

    /**
     * Resolve a bare symptom snake-case name to the matching `symptom.<name>`
     * [MetricDef]. Returns null when the symptom isn't in the canonical
     * registry (caller should fall back to `symptom.other` for free-text).
     */
    fun bySymptomName(name: String): MetricDef? = byType["symptom.$name"]

    /**
     * Rows surfaced in `MeasurementScreen` QUICK MEASURES — `measurement.*`
     * types with `discoverable_in_quick_log = true` in the TOML.
     */
    fun quickMeasures(): List<MetricDef> =
        all.filter { it.namespace == "measurement" && it.discoverableInQuickLog }
}
