#!/usr/bin/env bash
# OHDC v0 protobuf stubs are now generated by the shared package, not
# per-MCP. Forward to the shared script.
#
# To regenerate, run:
#
#     bash packages/python/ohd-shared/scripts/regen_proto.sh
#
# The generated stubs land at
# ``packages/python/ohd-shared/src/ohd_shared/_gen/ohdc/v0/`` and are
# consumed via the ``ohd-shared`` workspace path dep in this MCP's
# ``pyproject.toml``. See ``packages/python/ohd-shared/README.md``.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_SCRIPT="$(cd "$HERE/../../../packages/python/ohd-shared/scripts" && pwd)/regen_proto.sh"

if [[ ! -f "$SHARED_SCRIPT" ]]; then
  echo "shared regen script not found at $SHARED_SCRIPT" >&2
  exit 1
fi
exec bash "$SHARED_SCRIPT"
